name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/application-release.yaml@main
    with:
      application-name: codbex-salaries
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-salaries - ${{ github.event.inputs.releaseVersion }}
  
        Salaries Management Application
  
        ## Deployment
  
        ```
        docker run --name codbex-salaries \
        --rm -p 8080:8080 -p 8081:8081 \
        ghcr.io/codbex/codbex-salaries:${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-salaries/gen/](http://localhost:8080/services/web/codbex-salaries/gen/) - Admin Panel
    secrets: inherit
